### ISSUE TITLE
Documentation examples not working Chrome on Mac M2

### ISSUE THREAD

**Issue by john-guerra** [jpmorganchase/anu#28]
The following demo didn't work for me on Chrome, Macbook Pro M2

https://jpmorganchase.github.io/anu/examples/scatter_plot_3D.html

Console error:

```
BJS - [11:28:39]: Babylon.js v6.41.1 - WebGL2 - Parallel shader compilation
index.13ac89f3.js:4 BJS - [11:28:39]: Session mode "immersive-vr" not supported in browser
_LogEnabled @ index.13ac89f3.js:4
Warn @ index.13ac89f3.js:22
(anonymous) @ index.13ac89f3.js:7208
setHelperAsync @ index.13ac89f3.js:7208
await in setHelperAsync (async)
(anonymous) @ index.13ac89f3.js:7208
Promise.then (async)
CreateAsync @ index.13ac89f3.js:7208
dr.createDefaultXRExperienceAsync @ index.13ac89f3.js:7208
(anonymous) @ index.13ac89f3.js:37506
index.13ac89f3.js:31 Uncaught Error: required feature not compatible
    at qa.enableFeature (index.13ac89f3.js:31:216818)
    at index.13ac89f3.js:37506:2160207
enableFeature @ index.13ac89f3.js:31
(anonymous) @ index.13ac89f3.js:37506
favicon.ico:1 
        
        
       GET https://jpmorganchase.github.io/favicon.ico 404 (Not Found)
```

**Comment by dsaffo** [comment]
Wrapped webxr initializing code in a try catch for browsers that don't support it. Should be fixed now.
